# Generated by Django 5.1.3 on 2024-12-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farm',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
