# Generated by Django 5.1.3 on 2024-11-22 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='category',
        ),
        migrations.AlterModelTable(
            name='farm',
            table='farm',
        ),
        migrations.AlterModelTable(
            name='item',
            table='item',
        ),
    ]
